with EXTENDED_JOURNAL as (select CONCAT(SURNAME, ' ', STUDENT.NAME, ' ', SECOND_NAME) as NAME, STUDY_GROUP_ID, SUBJECT.NAME as SUBJECT, SUBJECT.ID as SUBJECT_ID, MARK.NAME as MARK, JOURNAL.COUNT AS ATTEMPTS from
((((JOURNAL
inner join STUDENT on JOURNAL.STUDENT_ID = STUDENT.ID)
inner join MARK on MARK_ID = MARK.ID)
inner join STUDY_PLAN on STUDY_PLAN_ID = STUDY_PLAN.ID)
inner join SUBJECT on STUDY_PLAN.SUBJECT_ID = SUBJECT.ID))

select PRIS.NAME as NAME,
       PRIS.STUDY_GROUP_ID as STUDY_GROUP,
       PRIS.MARK as PRIS_MARK,
       PRIS.ATTEMPTS as PRIS_ATTEMPTS,
       SII.MARK as SII_MARK,
       SII.ATTEMPTS as SII_ATTEMPTS
from EXTENDED_JOURNAL PRIS, EXTENDED_JOURNAL SII
where PRIS.SUBJECT_ID = 1 and SII.SUBJECT_ID = 2 and PRIS.NAME = SII.NAME;